version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily" # Check once a week
      time: "04:00"      # Optional: Runs at 4am
      timezone: "America/New_York"
    # removed the 'ignore' block so you get ALL updates
    open-pull-requests-limit: 10